import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";
import Sidebar from "@/components/sidebar/Sidebar";
import Rightbar from "@/components/rightbar/Rightbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.container}>
          <div className={styles.menu}>
            <Sidebar />
          </div>
          <div className={styles.content}>{children}</div>
          <div className={styles.side}>
            <Rightbar />
          </div>
        </div>
      </body>
    </html>
  );
}
